# Generated by Django 5.0.2 on 2025-01-28 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('valor', models.IntegerField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('inventario', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('categoria_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.categoria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_album', models.CharField(blank=True, max_length=30, null=True)),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='producto')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='producto')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='producto')),
                ('foto4', models.ImageField(blank=True, null=True, upload_to='producto')),
                ('foto5', models.ImageField(blank=True, null=True, upload_to='producto')),
                ('foto6', models.ImageField(blank=True, null=True, upload_to='producto')),
                ('producto_imagen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
    ]
