# Generated by Django 5.0.2 on 2025-01-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(auto_created=True)),
                ('nombre', models.CharField(max_length=30)),
                ('valor', models.IntegerField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('inventario', models.IntegerField()),
            ],
        ),
    ]
