# Generated by Django 5.0.2 on 2025-01-20 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto1', models.ImageField(upload_to='producto')),
                ('foto2', models.ImageField(upload_to='producto')),
                ('foto3', models.ImageField(upload_to='producto')),
                ('foto4', models.ImageField(upload_to='producto')),
                ('foto5', models.ImageField(upload_to='producto')),
                ('foto6', models.ImageField(upload_to='producto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('valor', models.IntegerField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('inventario', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.categoria')),
                ('imagen_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.imagen')),
            ],
        ),
    ]
