# Generated by Django 5.0.2 on 2025-01-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='foto1',
            field=models.ImageField(null=True, upload_to='producto'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='foto2',
            field=models.ImageField(null=True, upload_to='producto'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='foto3',
            field=models.ImageField(null=True, upload_to='producto'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='foto4',
            field=models.ImageField(null=True, upload_to='producto'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='foto5',
            field=models.ImageField(null=True, upload_to='producto'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='foto6',
            field=models.ImageField(null=True, upload_to='producto'),
        ),
    ]
