# Generated by Django 5.0.2 on 2025-02-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_imagen_foto1_alter_imagen_foto2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='foto1',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='foto2',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='foto3',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='foto4',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='foto5',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='foto6',
        ),
        migrations.AddField(
            model_name='producto',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to='producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='foto4',
            field=models.ImageField(blank=True, null=True, upload_to='producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='foto5',
            field=models.ImageField(blank=True, null=True, upload_to='producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='foto6',
            field=models.ImageField(blank=True, null=True, upload_to='producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(auto_created=True, default=True),
        ),
    ]
