# Generated by Django 5.0.2 on 2025-01-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_imagen_foto1_alter_imagen_foto2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='nombre_album',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
