# Generated by Django 5.0.2 on 2025-02-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_remove_imagen_foto1_remove_imagen_foto2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
