# Generated by Django 5.0.2 on 2025-01-26 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_remove_producto_imagen_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='usuario',
        ),
    ]
