# Generated by Django 5.0.2 on 2025-02-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='medida',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
