# Generated by Django 5.0.2 on 2025-01-26 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_alter_producto_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='usuario',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET, to=settings.AUTH_USER_MODEL),
        ),
    ]
