# Generated by Django 5.0.2 on 2025-01-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=11)),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('apellido_usuario', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('headshot', models.ImageField(upload_to='usuario')),
                ('admin', models.BooleanField()),
            ],
        ),
    ]
